// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5gBOJrK_zE5zlAVPEpii5w72KoGISmXM',
    appId: '1:696046258711:web:23a04afe72bcd888ea6a52',
    messagingSenderId: '696046258711',
    projectId: 'mind-mate-ai-c2f29',
    authDomain: 'mind-mate-ai-c2f29.firebaseapp.com',
    storageBucket: 'mind-mate-ai-c2f29.firebasestorage.app',
    measurementId: 'G-MNTCP1CKGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqYZ4LTLMWSKKykA1vgIni_9JTsrQyjYI',
    appId: '1:696046258711:android:299f40881bf9a5fdea6a52',
    messagingSenderId: '696046258711',
    projectId: 'mind-mate-ai-c2f29',
    storageBucket: 'mind-mate-ai-c2f29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRZw3sMR847iEIXbsBBIpXyFa7Xm0EXPo',
    appId: '1:696046258711:ios:481ad6e4b0af500eea6a52',
    messagingSenderId: '696046258711',
    projectId: 'mind-mate-ai-c2f29',
    storageBucket: 'mind-mate-ai-c2f29.firebasestorage.app',
    iosBundleId: 'com.example.mindmateai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRZw3sMR847iEIXbsBBIpXyFa7Xm0EXPo',
    appId: '1:696046258711:ios:481ad6e4b0af500eea6a52',
    messagingSenderId: '696046258711',
    projectId: 'mind-mate-ai-c2f29',
    storageBucket: 'mind-mate-ai-c2f29.firebasestorage.app',
    iosBundleId: 'com.example.mindmateai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5gBOJrK_zE5zlAVPEpii5w72KoGISmXM',
    appId: '1:696046258711:web:e12b52980c49ade6ea6a52',
    messagingSenderId: '696046258711',
    projectId: 'mind-mate-ai-c2f29',
    authDomain: 'mind-mate-ai-c2f29.firebaseapp.com',
    storageBucket: 'mind-mate-ai-c2f29.firebasestorage.app',
    measurementId: 'G-E983EYQDJJ',
  );
}
